"""
Document Export Module - Enhanced export functions for video summaries
Supports PDF, Word (.docx), and Markdown (.md) formats with notes-style formatting
"""

from datetime import datetime
from typing import Any
import io


def export_summary_markdown(summary_data: dict, transcription: str = "", refined_transcription: str = "", video_name: str = "Video") -> str:
    """Export summary as Markdown research analyst notes format."""
    md_content = f"""# 🔬 AI Research Analysis: {video_name}
**Generated on**: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}

---

## 🎯 Main Purpose
{summary_data.get("main_purpose", "N/A")}

---

## 💡 Key Insights
"""
    for insight in summary_data.get("key_insights", []):
        md_content += f"- {insight}\n"
    
    md_content += "\n---\n\n## 🧠 Important Concepts\n\n"
    concepts = summary_data.get("important_concepts", [])
    if concepts:
        md_content += ", ".join(f"`{c}`" for c in concepts)
    else:
        md_content += "N/A"
        
    md_content += "\n\n---\n\n## 📋 Structured Summary\n\n"
    md_content += summary_data.get("structured_summary", "N/A")

    md_content += "\n\n---\n\n## 🏷️ Keywords\n\n"
    keywords = summary_data.get("keywords", [])
    if keywords:
        md_content += ", ".join(f"`{k}`" for k in keywords)
    else:
        md_content += "N/A"
    
    md_content += "\n\n---\n\n## ⏱️ Important Timestamps\n\n"
    highlights = summary_data.get("timestamped_highlights", [])
    if highlights:
        for h in highlights:
            ts = h.get("timestamp", 0)
            title = h.get("title", "Highlight")
            desc = h.get("description", "")
            minutes = int(ts // 60)
            seconds = int(ts % 60)
            md_content += f"### [{minutes:02d}:{seconds:02d}] {title}\n\n{desc}\n\n"
    else:
        md_content += "No timestamped highlights available.\n"
    
    if refined_transcription:
        md_content += "\n---\n\n## ✍️ Refined Transcription (Clear Text)\n\n"
        md_content += refined_transcription
    
    if transcription:
        md_content += "\n---\n\n## 📄 Raw Transcription\n\n"
        md_content += transcription
    
    md_content += "\n\n---\n\n*Generated by AI Video Summarization Platform - Research Mode*\n"
    
    return md_content


def export_summary_word(summary_data: dict, transcription: str = "", refined_transcription: str = "", video_name: str = "Video") -> bytes | None:
    """Export summary as Word document (.docx) with research notes formatting."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
        
        doc = Document()
        
        # Title
        title = doc.add_heading(f'🔬 AI Research Analysis: {video_name}', 0)
        title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        
        # Metadata
        meta = doc.add_paragraph()
        meta.add_run(f"Generated on: ").bold = True
        meta.add_run(datetime.now().strftime("%B %d, %Y at %I:%M %p"))
        
        doc.add_paragraph("_" * 80)
        
        # Main Purpose
        doc.add_heading('🎯 Main Purpose', 1)
        doc.add_paragraph(summary_data.get("main_purpose", "N/A"))
        
        doc.add_paragraph("_" * 80)
        
        # Key Insights
        doc.add_heading('💡 Key Insights', 1)
        for insight in summary_data.get("key_insights", []):
            p = doc.add_paragraph(style='List Bullet')
            p.add_run(insight)
        
        doc.add_paragraph("_" * 80)
        
        # Important Concepts
        doc.add_heading('🧠 Important Concepts', 1)
        concepts = summary_data.get("important_concepts", [])
        doc.add_paragraph(", ".join(concepts) if concepts else "N/A")
        
        doc.add_paragraph("_" * 80)
        
        # Structured Summary
        doc.add_heading('📋 Structured Summary', 1)
        doc.add_paragraph(summary_data.get("structured_summary", "N/A"))
        
        doc.add_paragraph("_" * 80)
        
        # Keywords
        doc.add_heading('🏷️ Keywords', 1)
        keywords = summary_data.get("keywords", [])
        doc.add_paragraph(", ".join(keywords) if keywords else "N/A")
        
        doc.add_paragraph("_" * 80)
        
        # Timestamps
        doc.add_heading('⏱️ Important Timestamps', 1)
        highlights = summary_data.get("timestamped_highlights", [])
        if highlights:
            for h in highlights:
                ts = h.get("timestamp", 0)
                title = h.get("title", "Highlight")
                desc = h.get("description", "")
                minutes = int(ts // 60)
                seconds = int(ts % 60)
                
                doc.add_heading(f"[{minutes:02d}:{seconds:02d}] {title}", 3)
                doc.add_paragraph(desc)
        else:
            doc.add_paragraph("No timestamped highlights available.")
        
        # Transcription (optional)
        if refined_transcription:
            doc.add_page_break()
            doc.add_heading('✍️ Refined Transcription (Clear Text)', 1)
            doc.add_paragraph(refined_transcription)
            
        if transcription:
            doc.add_page_break()
            doc.add_heading('📄 Raw Transcription', 1)
            doc.add_paragraph(transcription)
        
        # Footer
        doc.add_paragraph("_" * 80)
        footer = doc.add_paragraph("Generated by AI Video Summarization Platform - Research Mode")
        footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        
        # Save to bytes
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()
        
    except ImportError:
        return None
    except Exception as e:
        print(f"Error creating Word document: {e}")
        return None


def export_summary_pdf_enhanced(summary_data: dict, transcription: str = "", refined_transcription: str = "", video_name: str = "Video") -> bytes | None:
    """Export summary as enhanced PDF with research notes formatting."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.enums import TA_CENTER
        import io
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, 
                               rightMargin=inch, leftMargin=inch,
                               topMargin=inch, bottomMargin=inch)
        
        styles = getSampleStyleSheet()
        story = []
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=22,
            textColor='#1E88E5',
            spaceAfter=20,
            alignment=TA_CENTER
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor='#1565C0',
            spaceAfter=10,
            spaceBefore=10
        )
        
        # Title
        story.append(Paragraph(f"🔬 AI Research Analysis: {video_name}", title_style))
        
        # Metadata
        meta_text = f"<b>Generated on:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
        story.append(Paragraph(meta_text, styles['Normal']))
        story.append(Spacer(1, 0.2*inch))
        
        # Main Purpose
        story.append(Paragraph("🎯 Main Purpose", heading_style))
        story.append(Paragraph(summary_data.get("main_purpose", "N/A"), styles['Normal']))
        
        # Key Insights
        story.append(Paragraph("💡 Key Insights", heading_style))
        for insight in summary_data.get("key_insights", []):
            story.append(Paragraph(f"• {insight}", styles['Normal']))
        
        # Important Concepts
        story.append(Paragraph("🧠 Important Concepts", heading_style))
        concepts = ", ".join(summary_data.get("important_concepts", []))
        story.append(Paragraph(concepts if concepts else "N/A", styles['Normal']))
        
        # Structured Summary
        story.append(Paragraph("📋 Structured Summary", heading_style))
        story.append(Paragraph(summary_data.get("structured_summary", "N/A"), styles['Normal']))
        
        # Keywords
        story.append(Paragraph("🏷️ Keywords", heading_style))
        keywords = ", ".join(summary_data.get("keywords", []))
        story.append(Paragraph(keywords if keywords else "N/A", styles['Normal']))
        
        # Timestamps
        story.append(Paragraph("⏱️ Important Timestamps", heading_style))
        highlights = summary_data.get("timestamped_highlights", [])
        if highlights:
            for h in highlights:
                ts = h.get("timestamp", 0)
                title = h.get("title", "Highlight")
                desc = h.get("description", "")
                minutes = int(ts // 60)
                seconds = int(ts % 60)
                story.append(Paragraph(f"<b>[{minutes:02d}:{seconds:02d}] {title}</b>", styles['Normal']))
                story.append(Paragraph(desc, styles['Normal']))
                story.append(Spacer(1, 0.1*inch))
        
        # Transcription (optional)
        if refined_transcription:
            story.append(PageBreak())
            story.append(Paragraph("✍️ Refined Transcription (Clear Text)", heading_style))
            story.append(Paragraph(refined_transcription, styles['Normal']))
            
        if transcription:
            story.append(PageBreak())
            story.append(Paragraph("📄 Raw Transcription", heading_style))
            story.append(Paragraph(transcription, styles['Normal']))
            
        # Build PDF
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
        
    except Exception as e:
        print(f"Error creating PDF: {e}")
        return None
